### ISSUE TITLE
rails db:seed is failing

### ISSUE THREAD

**Issue by nithinbekal** [redpanthers/alexa-keeper#46]
Relevant stacktrace:

```
NoMethodError: undefined method `websites' for nil:NilClass
.../db/seeds.rb:12:in `block in <top (required)>'
.../db/seeds.rb:11:in `each'
.../db/seeds.rb:11:in `<top (required)>'
```

This is because user used to have association `has_many :websites`, but now it is `has_many :collection_websites`.

@Nimmyjv Please fix this - `bin/setup` command should work out of the box for the project.

**Comment by nithinbekal** [comment]
Cleaning up outdated issues/PRs that I created. Feel free to reopen if this is still relevant.
